version: '3.8'

services:
  credit_risk:
    build: .
    container_name: credit_risk_app
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./best_models:/app/best_models
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
  
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
      - /app/node_modules